# Generated by Django 5.1.4 on 2025-01-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_mainpageimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='graph_num_vacancy',
            field=models.ImageField(upload_to='images/', verbose_name='График количества вакансий по годам'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='graph_salary_level',
            field=models.ImageField(upload_to='images/', verbose_name='График уровня зарплат по годам'),
        ),
        migrations.AlterField(
            model_name='geography',
            name='graph_salary_level_by_city',
            field=models.ImageField(upload_to='images/', verbose_name='График уровень зарплат по городам'),
        ),
        migrations.AlterField(
            model_name='geography',
            name='graph_vacancy_fraction_by_city',
            field=models.ImageField(upload_to='images/', verbose_name='График доля вакансий по городам'),
        ),
        migrations.AlterField(
            model_name='skillsset',
            name='graph_skills',
            field=models.ImageField(upload_to='images/', verbose_name='График по скиллам'),
        ),
        migrations.AlterField(
            model_name='statisticset',
            name='city_rate_vacancy_graph',
            field=models.ImageField(upload_to='images/', verbose_name='График доли вакансий по городам'),
        ),
        migrations.AlterField(
            model_name='statisticset',
            name='city_salary_graph',
            field=models.ImageField(upload_to='images/', verbose_name='График уровня зарплат по городам'),
        ),
        migrations.AlterField(
            model_name='statisticset',
            name='top20_skills_graph',
            field=models.ImageField(upload_to='images/', verbose_name='График топ 20 навыков по годам'),
        ),
        migrations.AlterField(
            model_name='statisticset',
            name='yearly_salary_graph',
            field=models.ImageField(upload_to='images/', verbose_name='График уровня зарплат по годам'),
        ),
        migrations.AlterField(
            model_name='statisticset',
            name='yearly_vacancy_count_graph',
            field=models.ImageField(upload_to='images/', verbose_name='График количества вакансий по годам'),
        ),
    ]
